---

- name: install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add deadsnakes PPA
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: apt cache update
  ansible.builtin.apt:
      update_cache: yes

- name: python venv | install python
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - "python{{ python_version }}"
      - "python{{ python_version }}-venv"
    state: present

- name: Install pip for Python  using ensurepip
  ansible.builtin.command: "python{{ python_version }} -m ensurepip --upgrade"
  args:
    creates: "/usr/local/bin/pip{{ python_version }}"

- name: Install setuptools for Python
  ansible.builtin.pip:
    name:
      - setuptools
      - packaging
    executable: "pip{{ python_version }}"
