---

- name: install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add deadsnakes PPA
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: apt cache update
  ansible.builtin.apt:
      update_cache: yes

- name: python3.12 venv | install python3
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3.12
      - python3.12-venv
    state: present

- name: Install pip for Python 3.12 using ensurepip
  ansible.builtin.command: python3.12 -m ensurepip --upgrade
  args:
    creates: "/usr/local/bin/pip3.12"

- name: Install setuptools for Python 3.12
  ansible.builtin.pip:
    name:
      - setuptools
      - packaging
    executable: pip3.12
